# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('imo_number', models.CharField(max_length=7)),
                ('user_id', models.PositiveIntegerField()),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DELETED', 'DELETED')], default='ACTIVE', max_length=7)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ship',
            unique_together=set([('imo_number', 'user_id')]),
        ),
    ]
